# Generated by Django 5.2 on 2025-04-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('price_per_night', models.FloatField()),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('image_urls', models.TextField()),
                ('ratings', models.FloatField()),
                ('description', models.TextField()),
                ('reviews', models.IntegerField()),
                ('amenities', models.TextField()),
                ('host_info', models.TextField()),
                ('property_type', models.CharField(max_length=100)),
            ],
        ),
    ]
